<!doctype html>
<html lang="en">
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!-- Bootstrap CSS -->
    <link rel="icon" type="image/x-icon" href="/img/nerd.png">
    <link rel="stylesheet" href="/css/bootstrap.min.css">
    <link rel="stylesheet" href="/css/custom.css">
    <title>NerdHub</title>
</head>

<body>
    <!-- Navigation bar -->
    <nav class="navbar navbar-expand navbar-dark bg-danger fixed-top">
        <div class="nav-item">
            <a class="float-left" href="/">
                <img src="/img/nerd.png" width="70" height="70" class="d-inline-block align-top" alt="">
            </a>
        </div>
        <div class="container navbar-text text-white">
            <a href="/">
                <h3 class="font-italic font-weight-bold">NerdHub</h3>
            </a>
        </div>
        <div class="navbar-item">
            <!-- if a user isn't logged in he sees the login and register buttons -->
            <?php if ($currentUser === null): ?>
            <ul class="navbar-nav">
                <li class="nav-item">
                    <a class="nav-link" href="/user/login"><b class="text-white">Login</b></a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="/user/register"><b class="text-white">Register</b></a>
                </li>
            </ul>
            <!-- otherwise if the user is logged in, he can see his username and the logout button -->
            <?php else: ?>
            <ul class="navbar-nav">
                <li class="nav-item">
                    <a class="nav-link" href="/user/logout"><b class="text-white">Logout</b></a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="/"><b class="text-white">Settings</b></a>
                </li>
            </ul>
            <?php endif; ?>
        </div>
    </nav>
    <br><br><br><br>
    <?php if (isset($currentUser)): ?>
    <p class="text-center sub-text font-weight-bold font-italic">Welcome! <br><b class="text-warning"><?= $currentUser->getUserName() ?></b></p>
    <?php endif ?>


