<?php include BP . DIRECTORY_SEPARATOR . 'view/templates/headerNavbar.phtml' ?>

<h2 class="container text-center">Update <i><?= $themeName ?></i></h2>
<br>
<form class="container justify-content-center" action="create" method="post" enctype="multipart/form-data">
    <div class="form-group">
        <label for="new_theme_name" class="text-right">Theme Name</label>
        <input type="text"  class="form-control" id="new_theme_name" name="new_theme_name" placeholder="example: Witcher">
    </div>
    <div class="form-group">
        <label for="new_theme_category">Theme Category</label>
        <input type="text" class="form-control" id="new_theme_category" name="new_theme_category" placeholder="example: Video Game">
    </div>
    <div class="form-group">
        <label for="new_theme_description">Theme Description</label>
        <textarea type="text" class="form-control" id="new_theme_description" name="new_theme_description" rows="5"></textarea>
    </div>

    <!-- image -->
    <div class="form-row text-sm-right">
        <input type="file" id="file" name="file">
    </div>
    <br><br><br><br>
    <div class="form-row">
    <button type="submit" name="submit" class="form-group btn btn-success float-right" >Update!</button>
    </div>
</form>

<?php include BP . DIRECTORY_SEPARATOR . 'view/templates/footer.phtml' ?>
