<br><br><br>
<!-- Footer -->
<div class="footer-copyright
            text-center text-white
            py-3 fixed-bottom bg-dark">
    Lobel Vetengl
        <a href="https://github.com/Wettey?tab=repositories" target="_blank">Github</a>

</div>



<script type="javascript" src="/js/bootstrap.min.js"></script>
<script type="javascript" src="/js/jquery.js"></script>
<script type="javascript" src="/js/custom.js"></script>
</body>
</html>
