<!doctype html>

<html lang="en">
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!-- Bootstrap CSS -->
    <link rel="icon" type="image/x-icon" href="/img/nerd.png">
    <link rel="stylesheet" href="/css/bootstrap.min.css">
    <link rel="stylesheet" href="/css/custom.css">
    <title>Nerdhub</title>
</head>

<body>
<!-- Navigation bar -->
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <a class="navbar-brand" href="/">
            <img src="/img/nerd.png" width="60" height="60" class="d-inline-block align-top" alt="">
        </a>
        <div class="container">
            <a class="navbar-brand text-danger" href="/">
                Nerdhub
            </a>
            <li class="navbar-text text-white">
                <h2>
                    Themes
                </h2>
            </li>
                <ul class="navbar-nav">
                    <li class="nav-item">
                        <a class="nav-link" href="/user/login"><b class="text-white">Login</b></a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="/user/register"><b class="text-white">Register</b></a>
                    </li>
                </ul>
            </div>
    </nav>
<!-- Other phtml files go after this comment -->
<br>