<?php include 'templates/headerNavbar.phtml' ?>

<div class="container">
    <h3 class="text-center text-white">Login</h3>
    <form method="post" action="/user/loginSubmit">
        <div class="form-group">
            <label for="email">Email</label>
            <input type="email" class="form-control" id="email" name="email" placeholder="example.joe@gmail.com">
        </div>
        <div class="form-group">
            <label for="password">Password</label>
            <input type="password" class="form-control" id="password" name="password" placeholder="examp@101">
        </div>
        <button type="submit" class="btn btn-success float-right">Login</button>
    </form>
</div>

<?php include 'templates/footer.phtml' ?>
