<?php include 'template/headerNavbar.phtml' ?>

<!-- Create new themes or browse existing ones with a little help from jquery -->
<?php if (isset($currentUser)):  ?>
    <div class="d-flex justify-content-center">
        <a href="/theme/new">
            <button class="btn btn-success">
                + New Theme
            </button>
        </a>
    </div>
<?php endif ?>

<br>
<div class="d-flex justify-content-center">
    <form class="form-inline my-lg-2">
        <input class="form-control mr-sm-2" type="search" placeholder="browse themes..." aria-label="Search">
    </form>
</div>

<br><br>

<!-- Themes pulled from our database -->
<div class="container">
    <div class="row justify-content-center">
        <?php foreach ($themes as $theme) : ?>
            <div class="col-sm-6">
                <a href="/story/index">
                <div class="card-img">
                    <div class="card-body  bg-transparent" style = "width: 22rem; " >
                        <h5 class="card-title text-center text-white"><b><?= $theme->getName() ?></b></h5>
                        <img class="card-img-top rounded"  src="<?= $theme->getImage_path() ?>" alt="missing image">
                        <p class="card-text text-center text-white"><b><?= $theme->getCategory() ?></b></p>
                        <p class="card-text text-center text-secondary"><i><?= $theme->getDescription() ?></i></p>
                        <!--
                        if the user is logged in he can edit or delete themes
                        otherwise, he can only see (read) the content
                        -->
                        <?php if ($currentUser && $currentUser->getId() == $theme->getUserId()): ?>
                            <a href="theme/delete?id=<?= $theme->getId() ?>" class="btn btn-danger float-left">Delete</a>
                            <a href="theme/edit?id=<?= $theme->getId() ?>" class="btn btn-warning float-right">Edit</a>
                        <?php endif; ?>
                    </div>
                </div>
                </a>
            </div>
        <?php endforeach; ?>
    </div>
</div>

<?php include 'template/footer.phtml' ?>

